### ISSUE TITLE
hi 可以加一个license吗？这样可以方便fork

### ISSUE THREAD

**Issue by candywater** [HeliumOctahelide/heliumoctahelide.github.io#11]

**Comment by HeliumOctahelide** [comment]
您可以随意fork这个项目，我对它没有任何版权要求。

**Comment by candywater** [comment]
严格意义上讲，如果人在欧美国家（基本上加入过TPP协议的成员国），按照欧美法系没有明确授权而引用的话，作者本人不起诉也可能被警察强制起诉（公诉），
不过有你这句话就足够了，证明授权过了。
